FROM quay.io/fairwinds/nova:3.6.4

USER root

RUN apk update &&\
    apk add curl

RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && \
    chmod 755 /usr/local/bin/kubectl && \
    chown root:root /usr/local/bin/kubectl

COPY ./entrypoint.sh entrypoint.sh

ENTRYPOINT ["sh", "entrypoint.sh"]
